# Introduction to Ensemble Models

In [1]:
#Max Voting
import pandas as pd

In [2]:
import numpy as np

In [3]:
data=pd.read_csv('data_cleaned.csv')

In [4]:
data.shape

(891, 25)

In [5]:
data.head()

Survived   Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0         0  22.0   7.2500         0         0         1           0   
1         1  38.0  71.2833         1         0         0           1   
2         1  26.0   7.9250         0         0         1           1   
3         1  35.0  53.1000         1         0         0           1   
4         0  35.0   8.0500         0         0         1           0   

   Sex_male  SibSp_0  SibSp_1  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0         1        0        1  ...        1        0        0        0   
1         0        0        1  ...        1        0        0        0   
2         0        1        0  ...        1        0        0        0   
3         0        0        1  ...        1        0        0        0   
4         1        1        0  ...        1        0        0        0   

   Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0        0        0        0           0           0           1  
1        0        0        0           1           0           0  
2        0        0        0           0           0           1  
3        0        0        0           0           0           1  
4        0        0        0           0           0           1  

[5 rows x 25 columns]

In [6]:
x=data.drop(['Survived'] , axis=1)
y=data['Survived']

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
train_x, valid_x,train_y,valid_y=train_test_split(x,y,random_state=101,stratify=y)

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [11]:
model1=LogisticRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10],model1.score(valid_x,valid_y)

C:\Users\Rita\anaconda3.x\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


(array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0], dtype=int64), 0.7757847533632287)

In [12]:
model2=KNeighborsClassifier(n_neighbors=5)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10],model2.score(valid_x,valid_y)

(array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0], dtype=int64), 0.7399103139013453)

In [13]:
model3=DecisionTreeClassifier(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10],model3.score(valid_x,valid_y)

(array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0], dtype=int64), 0.7757847533632287)

In [14]:
#Max Voting

In [15]:
from statistics import mode
final_pred=np.array([])
for i in range(0,len(valid_x)):
    final_pred=np.append(final_pred,mode([pred1[i],pred2[i],pred3[i]]))

In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(valid_y,final_pred)
accuracy_score(valid_y,pred1),accuracy_score(valid_y,pred2),accuracy_score(valid_y,pred3)

(0.7757847533632287, 0.7399103139013453, 0.7757847533632287)

# Averaging (Regression)

In [17]:
data=pd.read_csv('train_cleaned.csv')

In [18]:
x=data.drop(['Item_Outlet_Sales'], axis=1)
y=data['Item_Outlet_Sales']

In [19]:
from sklearn.model_selection import train_test_split
train_x, valid_x,train_y,valid_y=train_test_split(x,y,random_state=101,shuffle=False)


In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [21]:
model1=LinearRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10],model1.score(valid_x,valid_y)

(array([ 2443.32513354,  2788.36657095,  2169.73477778,  2385.33394477,
         2716.58813899,  3771.41850023,  5119.35227101,  4133.40997069,
        -1010.95412123,  1365.9929378 ]),
 0.5551582433748833)

In [22]:
model2=KNeighborsRegressor(n_neighbors=9)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10],model2.score(valid_x,valid_y)

(array([1859.06155556, 2519.09128889, 2620.88471111, 2277.33191111,
        3801.12617778, 4099.10866667, 5151.88642222, 5378.62831111,
         476.7128    , 1501.15706667]),
 0.5007936087911619)

In [23]:
model3=DecisionTreeRegressor(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10],model3.score(valid_x,valid_y)

(array([2413.81776312, 2822.71913115,  585.22631071, 2348.86112052,
        3153.22486811, 3544.38935413, 5815.65707727, 5048.681504  ,
         105.25188333, 1595.93215694]),
 0.5735111622038214)

In [24]:
from statistics import mean 
final_pred = np.array([])
for i in range (0, len(valid_x)):
    final_pred=np.append(final_pred,mean([pred1[i],pred2[i],pred3[i]]))

In [25]:
from sklearn.metrics import r2_score
r2_score(valid_y,final_pred)
r2_score(valid_y,pred1),r2_score(valid_y,pred2),r2_score(valid_y,pred3)

(0.5551582433748833, 0.5007936087911619, 0.5735111622038214)

In [26]:
r2_score(valid_y,final_pred)

0.5761404444862532

# Weighted Averaging

In [27]:
from statistics import mean

In [28]:
final_pred=np.array([])
for i in range (0,len(valid_x)):
    final_pred=np.append(final_pred,mean([pred1[i],pred1[i],pred2[i] , pred3[i], pred3[i]]))

In [29]:
from sklearn.metrics import r2_score

In [30]:
r2_score(valid_y,pred1),r2_score(valid_y,pred2),r2_score(valid_y,pred3)

(0.5551582433748833, 0.5007936087911619, 0.5735111622038214)

# Rank Averaging

In [31]:
m1_score=model1.score(valid_x,valid_y)
m2_score=model2.score(valid_x,valid_y)
m3_score=model3.score(valid_x,valid_y)
m1_score,m2_score,m3_score

(0.5551582433748833, 0.5007936087911619, 0.5735111622038214)

In [32]:
model1=LinearRegression()
model1.fit(train_x,train_y)
pred1=model1.predict(valid_x)
pred1[:10],model1.score(valid_x,valid_y)

(array([ 2443.32513354,  2788.36657095,  2169.73477778,  2385.33394477,
         2716.58813899,  3771.41850023,  5119.35227101,  4133.40997069,
        -1010.95412123,  1365.9929378 ]),
 0.5551582433748833)

In [33]:
model2=KNeighborsRegressor(n_neighbors=9)
model2.fit(train_x,train_y)
pred2=model2.predict(valid_x)
pred2[:10],model2.score(valid_x,valid_y)

(array([1859.06155556, 2519.09128889, 2620.88471111, 2277.33191111,
        3801.12617778, 4099.10866667, 5151.88642222, 5378.62831111,
         476.7128    , 1501.15706667]),
 0.5007936087911619)

In [34]:
model3=DecisionTreeRegressor(max_depth=7)
model3.fit(train_x,train_y)
pred3=model3.predict(valid_x)
pred3[:10],model3.score(valid_x,valid_y)

(array([2413.81776312, 2822.71913115,  585.22631071, 2348.86112052,
        3153.22486811, 3544.38935413, 5815.65707727, 5048.681504  ,
         105.25188333, 1595.93215694]),
 0.5734631265018326)

In [35]:
m1_score=model1.score(valid_x,valid_y)
m2_score=model2.score(valid_x,valid_y)
m3_score=model3.score(valid_x,valid_y)
m1_score,m2_score,m3_score

(0.5551582433748833, 0.5007936087911619, 0.5734631265018326)

In [36]:
index=[1,2,3]
valid_r2=[m1_score, m2_score,m3_score]
rank_eval=pd.DataFrame({'score' : valid_r2}, index=index_)
rank_eval

NameError: name 'index_' is not defined